//! Auditable Beta performance measurements over the real PowerShell host.
//!
//! This module intentionally owns no shell state and does not use the probe
//! event tap.  Each sample is observed from the same physical rows a user
//! sees in a ConPTY.  A cache-miss and a cache-hit run use the same per-
//! scenario data directory, while every measured query still gets its own
//! input, first-menu, and complete-dynamic-menu timestamp.

use crate::probe::Harness;
use anyhow::{Context, Result, bail, ensure};
use serde_json::{Value, json};
use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
    thread,
    time::{Duration, Instant},
};

const QUERY_BATCH: usize = 10;
const WAIT_TIMEOUT: Duration = Duration::from_secs(20);
const CLEANUP_TIMEOUT: Duration = Duration::from_millis(500);
const IDLE_CPU_SAMPLE: Duration = Duration::from_millis(200);
const OUTPUT_BYTES: usize = 256 * 1024;
const METRICS_SCHEMA: u32 = 1;
const MIN_ACCEPTANCE_SAMPLES: usize = 300;

#[derive(Clone, Copy)]
enum ScenarioKind {
    Root,
    Git,
    Cargo,
    JavaScript,
    Path,
    Fuzzy,
}

impl ScenarioKind {
    fn name(self) -> &'static str {
        match self {
            Self::Root => "root",
            Self::Git => "git",
            Self::Cargo => "cargo",
            Self::JavaScript => "js",
            Self::Path => "path",
            Self::Fuzzy => "fuzzy",
        }
    }

    fn description(self) -> &'static str {
        match self {
            Self::Root => "首词命令索引",
            Self::Git => "Git 本地分支动态值",
            Self::Cargo => "Cargo features 动态值",
            Self::JavaScript => "npm scripts 动态值",
            Self::Path => "PowerShell 目录路径",
            Self::Fuzzy => "模糊匹配命令",
        }
    }

    fn dynamic(self) -> bool {
        matches!(
            self,
            Self::Git | Self::Cargo | Self::JavaScript | Self::Path
        )
    }

    fn cwd(self, fixtures: &Fixtures) -> &Path {
        match self {
            Self::Root | Self::Fuzzy => &fixtures.root,
            Self::Git => &fixtures.git,
            Self::Cargo => &fixtures.cargo_app,
            Self::JavaScript => &fixtures.javascript,
            Self::Path => &fixtures.paths,
        }
    }

    fn line(self, index: usize) -> String {
        match self {
            Self::Root => format!("ssbeta-root-{index}"),
            Self::Git => format!("git switch ssbeta-git-{index}"),
            Self::Cargo => format!("cargo build --features ssbeta-cargo-{index}"),
            Self::JavaScript => format!("npm run ssbeta-js-{index}"),
            Self::Path => format!("cd ssbeta-path-{index}"),
            Self::Fuzzy => format!("ssbf{index}"),
        }
    }

    fn expected(self, index: usize) -> String {
        match self {
            Self::Root => format!("ssbeta-root-{index}"),
            Self::Git => format!("ssbeta-git-{index}"),
            Self::Cargo => format!("ssbeta-cargo-{index}"),
            Self::JavaScript => format!("ssbeta-js-{index}"),
            Self::Path => format!("ssbeta-path-{index}"),
            Self::Fuzzy => format!("ssbeta-fuzzy-{index}"),
        }
    }
}

const SCENARIOS: [ScenarioKind; 6] = [
    ScenarioKind::Root,
    ScenarioKind::Git,
    ScenarioKind::Cargo,
    ScenarioKind::JavaScript,
    ScenarioKind::Path,
    ScenarioKind::Fuzzy,
];

struct Fixtures {
    root: PathBuf,
    bin: PathBuf,
    git: PathBuf,
    cargo_app: PathBuf,
    javascript: PathBuf,
    paths: PathBuf,
    throughput: PathBuf,
}

struct TemporaryDirectory {
    path: PathBuf,
}

impl TemporaryDirectory {
    fn new() -> Result<Self> {
        let path = env::temp_dir().join(format!("blueberry-beta-metrics-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&path)
            .with_context(|| format!("无法创建性能夹具目录 {}", path.display()))?;
        Ok(Self { path })
    }
}

impl Drop for TemporaryDirectory {
    fn drop(&mut self) {
        // This path contains a UUID generated by this run and is never taken
        // from user input.  Cleanup is best effort so a useful report/error
        // is not replaced by a secondary filesystem failure.
        let _ = fs::remove_dir_all(&self.path);
    }
}

#[derive(Default)]
struct Measurements {
    first_query: Vec<f64>,
    first_dynamic_query: Vec<f64>,
    actual_transport: Vec<String>,
    input_echo: Vec<f64>,
    first_menu: Vec<f64>,
    first_candidate_menu: Vec<f64>,
    dynamic_complete_menu: Vec<f64>,
    eligible_first_candidate_menu: Vec<f64>,
    eligible_dynamic_complete_menu: Vec<f64>,
    memory_prompt: Vec<u64>,
    memory_menu: Vec<u64>,
    idle_cpu: Vec<f64>,
    throughput: Vec<f64>,
    transport_ineligible_hot_queries: usize,
    missing_input_echo: usize,
    missing_first_menu: usize,
    missing_first_candidate_menu: usize,
    missing_dynamic_complete_menu: usize,
}

struct Observation {
    input_echo: f64,
    first_menu: f64,
    first_candidate_menu: f64,
    dynamic_complete_menu: Option<f64>,
}

impl Measurements {
    fn record(&mut self, observation: Observation, dynamic: bool, transport_valid: bool) {
        self.input_echo.push(observation.input_echo);
        self.first_menu.push(observation.first_menu);
        self.first_candidate_menu
            .push(observation.first_candidate_menu);
        if transport_valid {
            self.eligible_first_candidate_menu
                .push(observation.first_candidate_menu);
        } else {
            self.transport_ineligible_hot_queries += 1;
        }
        if let Some(value) = observation.dynamic_complete_menu {
            self.dynamic_complete_menu.push(value);
            if transport_valid {
                self.eligible_dynamic_complete_menu.push(value);
            }
        } else if dynamic {
            self.missing_dynamic_complete_menu += 1;
        }
    }

    fn report(&self, expected_queries: usize, expected_sessions: usize) -> Value {
        json!({
            "queries": expected_queries,
            "sessions": expected_sessions,
            "first_dynamic_query": f64_stats(&self.first_dynamic_query, "ms"),
            "first_query": f64_stats(&self.first_query, "ms"),
            "actual_transport": &self.actual_transport,
            "transport_ineligible_hot_queries": self.transport_ineligible_hot_queries,
            "input_echo": f64_stats(&self.input_echo, "ms"),
            "first_menu": f64_stats(&self.first_menu, "ms"),
            "first_candidate_menu": f64_stats(&self.first_candidate_menu, "ms"),
            "dynamic_complete_menu": f64_stats(&self.dynamic_complete_menu, "ms"),
            "transport_eligible_first_candidate_menu": f64_stats(&self.eligible_first_candidate_menu, "ms"),
            "transport_eligible_dynamic_complete_menu": f64_stats(&self.eligible_dynamic_complete_menu, "ms"),
            "memory_prompt": u64_stats(&self.memory_prompt, "bytes"),
            "memory_menu": u64_stats(&self.memory_menu, "bytes"),
            "idle_cpu": f64_stats(&self.idle_cpu, "percent"),
            "throughput": f64_stats(&self.throughput, "bytes_per_second"),
            "missing": {
                "input_echo": self.missing_input_echo,
                "first_menu": self.missing_first_menu,
                "first_candidate_menu": self.missing_first_candidate_menu,
                "dynamic_complete_menu": self.missing_dynamic_complete_menu,
            },
        })
    }

    fn acceptance_values(&self, dynamic: bool) -> &[f64] {
        if dynamic {
            &self.eligible_dynamic_complete_menu
        } else {
            &self.eligible_first_candidate_menu
        }
    }

    fn acceptance_report(&self, expected_queries: usize, dynamic: bool) -> Value {
        let values = self.acceptance_values(dynamic);
        let statistics = f64_stats(values, "ms");
        let p95 = statistics.get("p95").and_then(Value::as_f64);
        let status = if self.transport_ineligible_hot_queries != 0 {
            "transport_mismatch"
        } else if values.len() != expected_queries {
            "incomplete"
        } else if p95.is_some_and(|value| value <= 20.0) {
            "passed"
        } else {
            "failed"
        };
        json!({
            "metric": if dynamic { "dynamic_complete_menu" } else { "first_candidate_menu" },
            "statistics": statistics,
            "expected_samples": expected_queries,
            "observed_samples": values.len(),
            "p95_limit_ms": 20.0,
            "status": status,
        })
    }
}

/// Run the Beta acceptance harness.
///
/// `samples` is the number of measured queries per scenario and per cache
/// mode.  Queries are grouped into ten-query ConPTY sessions, but all samples
/// are retained in the returned JSON.  A value of 10 is suitable for a smoke
/// run; the formal plan uses 300.  The caller chooses the executable and
/// PowerShell path so the same function can measure a release artifact.
pub fn run(
    executable: &Path,
    shell: &Path,
    samples: u16,
    descriptions: bool,
    transport: &str,
) -> Result<Value> {
    ensure!(samples > 0, "性能样本数必须大于 0");
    let transport = transport.to_ascii_lowercase();
    ensure!(
        matches!(transport.as_str(), "osc" | "pipe"),
        "transport 必须是 osc 或 pipe（收到 {transport}）"
    );
    ensure!(
        !executable.as_os_str().is_empty(),
        "Blueberry 可执行文件路径不能为空"
    );
    ensure!(!shell.as_os_str().is_empty(), "PowerShell 路径不能为空");

    let temporary = TemporaryDirectory::new()?;
    let fixtures = create_fixtures(&temporary.path)?;
    let config = temporary.path.join("beta-config.toml");
    write_config(&config, descriptions)?;
    let environment = host_environment(&fixtures)?;
    let sample_count = usize::from(samples);
    let session_count = sample_count.div_ceil(QUERY_BATCH);

    let mut scenario_reports = Vec::with_capacity(SCENARIOS.len());
    let mut all_first_query = Vec::new();
    let mut all_first_dynamic_query = Vec::new();
    let mut all_echo = Vec::new();
    let mut all_dynamic = Vec::new();
    let mut all_dynamic_eligible = Vec::new();
    let mut all_hot_eligible = Vec::new();
    let mut actual_transports = Vec::new();
    let mut total_missing = 0usize;
    let mut acceptance_failures = Vec::new();
    for kind in SCENARIOS {
        let data_dir = temporary.path.join("data").join(kind.name());
        fs::create_dir_all(&data_dir)?;
        let cache_runs = measure_cache_modes(
            executable,
            shell,
            &config,
            &fixtures,
            &environment,
            kind,
            sample_count,
            &data_dir,
            &transport,
        )?;
        let miss = cache_runs.miss;
        let hit = cache_runs.hit;
        all_echo.extend(miss.input_echo.iter().copied());
        all_echo.extend(hit.input_echo.iter().copied());
        all_dynamic.extend(miss.dynamic_complete_menu.iter().copied());
        all_dynamic.extend(hit.dynamic_complete_menu.iter().copied());
        all_dynamic_eligible.extend(miss.eligible_dynamic_complete_menu.iter().copied());
        all_dynamic_eligible.extend(hit.eligible_dynamic_complete_menu.iter().copied());
        all_hot_eligible.extend(miss.acceptance_values(kind.dynamic()).iter().copied());
        all_hot_eligible.extend(hit.acceptance_values(kind.dynamic()).iter().copied());
        all_first_query.extend(miss.first_query.iter().copied());
        all_first_query.extend(hit.first_query.iter().copied());
        all_first_dynamic_query.extend(miss.first_dynamic_query.iter().copied());
        all_first_dynamic_query.extend(hit.first_dynamic_query.iter().copied());
        actual_transports.extend(miss.actual_transport.iter().cloned());
        actual_transports.extend(hit.actual_transport.iter().cloned());
        total_missing += miss.missing_input_echo
            + miss.missing_first_menu
            + miss.missing_first_candidate_menu
            + miss.missing_dynamic_complete_menu
            + hit.missing_input_echo
            + hit.missing_first_menu
            + hit.missing_first_candidate_menu
            + hit.missing_dynamic_complete_menu;
        let miss_acceptance = miss.acceptance_report(sample_count, kind.dynamic());
        let hit_acceptance = hit.acceptance_report(sample_count, kind.dynamic());
        for (mode, report) in [
            ("cache_miss", &miss_acceptance),
            ("cache_hit", &hit_acceptance),
        ] {
            if report["status"] != "passed" {
                acceptance_failures.push(format!(
                    "{} {} 热态 {}（观测 {}/{}）",
                    kind.name(),
                    mode,
                    report["status"].as_str().unwrap_or("unknown"),
                    report["observed_samples"].as_u64().unwrap_or(0),
                    sample_count,
                ));
            }
        }
        let baseline = measure_pwsh_baseline(shell, kind.cwd(&fixtures), &environment, &fixtures)?;
        scenario_reports.push(json!({
            "name": kind.name(),
            "description": kind.description(),
            "dynamic": kind.dynamic(),
            "cache_miss": miss.report(sample_count, session_count),
            "cache_hit": hit.report(sample_count, session_count),
            "acceptance": {
                "cache_miss": miss_acceptance,
                "cache_hit": hit_acceptance,
            },
            "cache": {
                "definition": "每个 session pair 的 miss 使用全新 data 目录；随后 hit 复用同一份已验证 complete commands.json",
                "pairs": cache_runs.pairs,
            },
            "same_pwsh_baseline": baseline,
        }));
    }

    let echo_stats = f64_stats(&all_echo, "ms");
    let first_query_stats = f64_stats(&all_first_query, "ms");
    let first_dynamic_query_stats = f64_stats(&all_first_dynamic_query, "ms");
    let dynamic_stats = f64_stats(&all_dynamic, "ms");
    let target_dynamic_stats = f64_stats(&all_dynamic_eligible, "ms");
    let target_hot_stats = f64_stats(&all_hot_eligible, "ms");
    let dynamic_p95 = target_dynamic_stats.get("p95").and_then(Value::as_f64);
    let hot_p95 = target_hot_stats.get("p95").and_then(Value::as_f64);
    let mut reasons = Vec::new();
    if sample_count < MIN_ACCEPTANCE_SAMPLES {
        reasons.push(format!(
            "每种 cache 模式只有 {sample_count} 个热态样本，正式验收至少需要 {MIN_ACCEPTANCE_SAMPLES} 个"
        ));
    }
    if total_missing != 0 {
        reasons.push(format!("存在 {total_missing} 个未观测样本"));
    }
    if hot_p95.is_none_or(|value| value > 20.0) {
        reasons.push("热态菜单 P95 超过 20 ms 或无可用样本".to_owned());
    }
    reasons.extend(acceptance_failures);
    let transport_degraded = actual_transports.iter().any(|actual| actual != &transport);
    if transport_degraded {
        reasons.push(format!(
            "请求 transport={transport}，但适配器报告了降级 transport；这些样本不计作请求通道验收"
        ));
    }
    let passed = reasons.is_empty();

    Ok(json!({
        "schema": METRICS_SCHEMA,
        "build": if cfg!(debug_assertions) { "debug" } else { "release" },
        "platform": env::consts::OS,
        "arch": env::consts::ARCH,
        "executable": executable,
        "shell": shell,
        "samples_per_cache_mode": sample_count,
        "queries_per_session": QUERY_BATCH,
        "sessions_per_cache_mode": session_count,
        "minimum_acceptance_samples_per_cache_mode": MIN_ACCEPTANCE_SAMPLES,
        "acceptance_sample_count_ok": sample_count >= MIN_ACCEPTANCE_SAMPLES,
        "descriptions": descriptions,
        "transport": transport,
        "actual_transports": actual_transports,
        "transport_degraded": transport_degraded,
        "profile_mode": "preserved",
        "no_history": true,
        "trace": "disabled",
        "os_cache_cleared": false,
        "target": {
            "startup": {
                "status": "not_measured",
                "reason": "启动增量由独立 probe --with-profile 配对测量；本 harness 只记录提示符后的输入回显",
            },
            "complete_dynamic_menu": target_dynamic_stats,
            "complete_dynamic_menu_p95_ms": dynamic_p95,
            "hot_menu": target_hot_stats,
            "hot_menu_p95_ms": hot_p95,
            "limits": {"startup_increment_p50_ms": 50.0, "hot_menu_p95_ms": 20.0},
            "status": if passed { "passed" } else { "failed" },
            "reasons": reasons,
        },
        "overall": {
            "first_query": first_query_stats,
            "first_dynamic_query": first_dynamic_query_stats,
            "input_echo": echo_stats,
            "complete_dynamic_menu": dynamic_stats,
        },
        "scenarios": scenario_reports,
        "method": {
            "host": "每个样本都在真实 PowerShell + Blueberry + 外层 ConPTY 中测量",
            "observation": "只读取 Harness 的 viewport 行；输入回显和带候选图标的真实菜单行分别确认",
            "dynamic": "计时前确认无旧输入/菜单；动态结果须出现目标候选和完整可见的 F1 状态行且无加载标记。诊断替代或裁切状态行不算完成；静态场景不计作动态完成",
            "ordering": "每场景每种 cache 模式使用 0..9 循环的十个唯一夹具候选",
            "initial_query": "每个 session 的首个查询单独等待完整动态结果；它不进入热态菜单统计。静态场景的首个查询只等待首个可用候选",
            "cache": "每个 session pair 先在全新空 data 目录测量 miss，再复用同一份已验证 complete=true 的 commands.json 测量 hit；hit 后检查文件时间未改变",
            "transport": "每个 host 读取新建 session 的 adapter.json；只有与请求 transport 相同的热态样本进入验收统计，降级样本只保留为诊断",
            "memory": "Windows 采样 Blueberry host working set；其他平台报告 unavailable",
            "cpu": "Windows 使用 GetProcessTimes，空闲约 200 ms；其他平台报告 unavailable",
            "throughput": "固定安全文本夹具通过 Get-Content -Raw 输出，并用独立 pwsh 同命令作基准",
            "profile": "不传 --no-profile；BLUEBERRY_NO_HISTORY=1 只禁止历史落盘，不改变 profile 加载",
            "trace": "未设置 trace 路径，BLUEBERRY_TRACE=0",
            "cache_state": "保留 OS 文件缓存，不清空系统缓存",
        },
        "fixture": {
            "root": fixtures.root,
            "git": fixtures.git,
            "cargo": fixtures.cargo_app,
            "javascript": fixtures.javascript,
            "paths": fixtures.paths,
            "throughput_bytes": OUTPUT_BYTES,
        },
    }))
}

struct CacheMeasurements {
    miss: Measurements,
    hit: Measurements,
    pairs: Vec<Value>,
}

#[allow(clippy::too_many_arguments)]
fn measure_cache_modes(
    executable: &Path,
    shell: &Path,
    config: &Path,
    fixtures: &Fixtures,
    environment: &BTreeMap<String, String>,
    kind: ScenarioKind,
    samples: usize,
    data_root: &Path,
    transport: &str,
) -> Result<CacheMeasurements> {
    let sessions = samples.div_ceil(QUERY_BATCH);
    let mut miss_measurements = Measurements::default();
    let mut hit_measurements = Measurements::default();
    let mut pairs = Vec::with_capacity(sessions);
    let mut completed_queries = 0usize;
    for session_index in 0..sessions {
        let remaining = samples.saturating_sub(completed_queries);
        let query_count = remaining.min(QUERY_BATCH);
        ensure!(query_count > 0, "场景 {} 产生了空性能批次", kind.name());
        // Each pair gets a fresh directory.  This keeps every miss sample a
        // real index-cache miss instead of making only the first session a
        // miss and silently measuring later sessions as hits.
        let pair_dir = data_root.join(format!("pair-{session_index}"));
        fs::create_dir_all(&pair_dir)?;
        ensure!(
            fs::read_dir(&pair_dir)?.next().is_none(),
            "场景 {} session {} 的 miss 目录不是空目录，拒绝把旧缓存当作 miss",
            kind.name(),
            session_index
        );
        let miss = measure_session(
            executable,
            shell,
            config,
            fixtures,
            environment,
            kind,
            session_index % 10,
            query_count,
            &pair_dir,
            transport,
            session_index,
            "miss",
        )?;
        let miss_transport = miss.actual_transport.clone();
        let cache_complete = verify_complete_cache(&pair_dir)?;
        let cache_path = pair_dir.join("commands.json");
        let before = fs::metadata(&cache_path)
            .with_context(|| format!("无法读取 miss 缓存时间 {}", cache_path.display()))?
            .modified()
            .with_context(|| format!("无法读取 miss 缓存修改时间 {}", cache_path.display()))?;
        let hit = measure_session(
            executable,
            shell,
            config,
            fixtures,
            environment,
            kind,
            session_index % 10,
            query_count,
            &pair_dir,
            transport,
            session_index,
            "hit",
        )?;
        let hit_transport = hit.actual_transport.clone();
        let after = fs::metadata(&cache_path)
            .with_context(|| format!("无法读取 hit 缓存时间 {}", cache_path.display()))?
            .modified()
            .with_context(|| format!("无法读取 hit 缓存修改时间 {}", cache_path.display()))?;
        let rewritten = before != after;
        ensure!(
            !rewritten,
            "场景 {} session {} 的 cache-hit 意外重写 commands.json",
            kind.name(),
            session_index
        );
        append_measurements(&mut miss_measurements, miss);
        append_measurements(&mut hit_measurements, hit);
        pairs.push(json!({
            "session": session_index,
            "queries": query_count,
            "miss_complete": cache_complete,
            "hit_complete": verify_complete_cache(&pair_dir)?,
            "rewritten_on_hit": rewritten,
            "miss_transport": miss_transport,
            "hit_transport": hit_transport,
        }));
        if (session_index + 1) % 5 == 0 || session_index + 1 == sessions {
            eprintln!(
                "beta metrics: {} cache pairs {}/{}",
                kind.name(),
                session_index + 1,
                sessions
            );
        }
        completed_queries += query_count;
    }
    ensure!(
        completed_queries == samples
            && miss_measurements.input_echo.len() == samples
            && hit_measurements.input_echo.len() == samples,
        "场景 {} 的 miss/hit 未完成全部 {} 个热态查询（完成 {}）",
        kind.name(),
        samples,
        completed_queries
    );
    Ok(CacheMeasurements {
        miss: miss_measurements,
        hit: hit_measurements,
        pairs,
    })
}

fn append_measurements(target: &mut Measurements, mut source: Measurements) {
    target.first_query.append(&mut source.first_query);
    target
        .first_dynamic_query
        .append(&mut source.first_dynamic_query);
    target.actual_transport.append(&mut source.actual_transport);
    target.input_echo.append(&mut source.input_echo);
    target.first_menu.append(&mut source.first_menu);
    target
        .first_candidate_menu
        .append(&mut source.first_candidate_menu);
    target
        .dynamic_complete_menu
        .append(&mut source.dynamic_complete_menu);
    target
        .eligible_first_candidate_menu
        .append(&mut source.eligible_first_candidate_menu);
    target
        .eligible_dynamic_complete_menu
        .append(&mut source.eligible_dynamic_complete_menu);
    target.memory_prompt.append(&mut source.memory_prompt);
    target.memory_menu.append(&mut source.memory_menu);
    target.idle_cpu.append(&mut source.idle_cpu);
    target.throughput.append(&mut source.throughput);
    target.transport_ineligible_hot_queries += source.transport_ineligible_hot_queries;
    target.missing_input_echo += source.missing_input_echo;
    target.missing_first_menu += source.missing_first_menu;
    target.missing_first_candidate_menu += source.missing_first_candidate_menu;
    target.missing_dynamic_complete_menu += source.missing_dynamic_complete_menu;
}

#[allow(clippy::too_many_arguments)]
fn measure_session(
    executable: &Path,
    shell: &Path,
    config: &Path,
    fixtures: &Fixtures,
    environment: &BTreeMap<String, String>,
    kind: ScenarioKind,
    first_index: usize,
    query_count: usize,
    data_dir: &Path,
    transport: &str,
    session_index: usize,
    mode: &str,
) -> Result<Measurements> {
    let args = host_args(config, shell, data_dir, transport);
    let cwd = kind.cwd(fixtures);
    let token = uuid::Uuid::new_v4().to_string();
    // StatusWriter creates one session-UUID directory per host.  Keep the
    // pre-existing paths so a cache-hit run cannot accidentally report the
    // previous miss session's adapter.json (both use the same data directory).
    let previous_adapters = adapter_paths(data_dir);
    let mut harness = Harness::start(executable, &args, cwd, environment, token)
        .with_context(|| format!("无法启动 {} 场景的 Blueberry host", kind.name()))?;
    wait_for_prompt(&mut harness, WAIT_TIMEOUT)
        .with_context(|| format!("{} 场景等待 PowerShell 提示符失败", kind.name()))?;
    // StatusWriter publishes the transport selected by the adapter in a
    // session-specific adapter.json.  Observe it before recording any query
    // so a pipe fallback can never be included in the requested-pipe sample.
    let actual_transport = wait_for_transport(data_dir, transport, &previous_adapters)?;
    let transport_valid = actual_transport == transport;
    let mut measurements = Measurements::default();
    measurements.actual_transport.push(actual_transport);
    sample_memory(&mut measurements.memory_prompt, &harness);

    // The first query is intentionally kept out of the hot arrays.  It
    // measures startup/initial dynamic readiness for this fresh process; the
    // following ten-query batch is the hot sample set.
    let first_index = first_index % 10;
    let first_line = kind.line(first_index);
    let first_expected = kind.expected(first_index);
    let first_observation =
        observe_query(&mut harness, &first_line, &first_expected, kind.dynamic())
            .with_context(|| format!("{} 场景首次查询未完成", kind.name()))?;
    let initial_query = first_observation
        .dynamic_complete_menu
        .unwrap_or(first_observation.first_candidate_menu);
    measurements.first_query.push(initial_query);
    if kind.dynamic() {
        measurements.first_dynamic_query.push(initial_query);
    }
    sample_memory(&mut measurements.memory_menu, &harness);
    reset_line(&mut harness, &first_line)?;
    let control_line = "ssbeta-root-0";
    observe_query(&mut harness, control_line, control_line, false)
        .with_context(|| format!("{} 场景控制查询未达到 complete 状态", kind.name()))?;
    reset_line(&mut harness, control_line)?;

    let mut previous_line = None;
    for offset in 0..query_count {
        if let Some(previous_line) = previous_line.as_deref() {
            reset_line(&mut harness, previous_line)?;
        }
        let index = (first_index + offset) % 10;
        let line = kind.line(index);
        let expected = kind.expected(index);
        let observation = observe_query(&mut harness, &line, &expected, kind.dynamic())
            .with_context(|| format!("{} 场景查询 `{line}` 未完成", kind.name()))?;
        measurements.record(observation, kind.dynamic(), transport_valid);
        sample_memory(&mut measurements.memory_menu, &harness);
        previous_line = Some(line);
    }

    if let Some(previous_line) = previous_line.as_deref() {
        reset_line(&mut harness, previous_line)?;
    }

    if let Some(cpu) = idle_cpu_percent(&harness) {
        measurements.idle_cpu.push(cpu);
    }
    let throughput = measure_throughput(&mut harness, &fixtures.throughput, session_index, mode)?;
    measurements.throughput.push(throughput);
    harness
        .finish(WAIT_TIMEOUT)
        .with_context(|| format!("{} 场景结束 host 失败", kind.name()))?;
    Ok(measurements)
}

fn observe_query(
    harness: &mut Harness,
    line: &str,
    expected: &str,
    dynamic: bool,
) -> Result<Observation> {
    let before = harness.viewport_contents();
    if has_input_echo(&before, line) || has_menu_row(&before) {
        bail!("计时前仍有本次输入或旧菜单，拒绝使用陈旧画面作为样本；screen:\n{before}");
    }
    let started = Instant::now();
    harness.send(line.as_bytes())?;
    let deadline = started + WAIT_TIMEOUT;
    let mut input_echo = None;
    let mut first_menu = None;
    let mut first_candidate_menu = None;
    let mut dynamic_complete_menu = None;
    loop {
        let screen = harness.viewport_contents();
        if input_echo.is_none() && has_input_echo(&screen, line) {
            input_echo = Some(milliseconds(started.elapsed()));
        }
        if input_echo.is_some() {
            if first_menu.is_none() && has_menu_row(&screen) {
                first_menu = Some(milliseconds(started.elapsed()));
            }
            if first_candidate_menu.is_none()
                && has_expected_menu_row(&screen, expected)
                && (dynamic || has_complete_status(&screen))
            {
                first_candidate_menu = Some(milliseconds(started.elapsed()));
            }
            if dynamic {
                if dynamic_complete_menu.is_none()
                    && has_expected_menu_row(&screen, expected)
                    && has_complete_status(&screen)
                {
                    dynamic_complete_menu = Some(milliseconds(started.elapsed()));
                }
            } else if has_expected_menu_row(&screen, expected) && has_complete_status(&screen) {
                dynamic_complete_menu = Some(milliseconds(started.elapsed()));
            }
        }
        let complete = dynamic_complete_menu.is_some();
        if complete {
            let input_echo = input_echo.context("当前输入没有在 viewport 中回显")?;
            let first_menu = first_menu.context("viewport 中没有真实候选菜单行")?;
            let first_candidate_menu = first_candidate_menu.context("目标候选尚未在菜单中出现")?;
            return Ok(Observation {
                input_echo,
                first_menu,
                first_candidate_menu,
                dynamic_complete_menu: if dynamic { dynamic_complete_menu } else { None },
            });
        }
        if Instant::now() >= deadline {
            bail!("等待回显/菜单/动态完成超时；expected={expected}; screen:\n{screen}");
        }
        pump_brief(harness, deadline);
    }
}

fn wait_for_prompt(harness: &mut Harness, timeout: Duration) -> Result<()> {
    let deadline = Instant::now() + timeout;
    loop {
        let screen = harness.viewport_contents();
        if has_prompt(&screen) {
            return Ok(());
        }
        if Instant::now() >= deadline {
            bail!("等待提示符超时；screen:\n{screen}");
        }
        pump_brief(harness, deadline);
    }
}

fn reset_line(harness: &mut Harness, previous_line: &str) -> Result<()> {
    // Every benchmark query is ASCII. SelectAll in Windows PSReadLine mode,
    // then delete the known input. These are ordinary editing keys only;
    // sending Escape next to a control byte can be decoded by ConPTY as an
    // Alt chord and leaves part of the previous query in the buffer.
    harness.send(b"\x01\x7f")?; // SelectAll + Backspace in one input write.
    let deadline = Instant::now() + CLEANUP_TIMEOUT;
    while Instant::now() < deadline {
        let screen = harness.viewport_contents();
        if !has_menu_row(&screen) && !has_input_echo(&screen, previous_line) {
            return Ok(());
        }
        pump_brief(harness, deadline);
    }
    bail!(
        "未确认上一条性能夹具输入和菜单已清除，拒绝继续计时；screen:\n{}",
        harness.viewport_contents()
    )
}

fn pump_brief(harness: &mut Harness, deadline: Instant) {
    let remaining = deadline.saturating_duration_since(Instant::now());
    if remaining.is_zero() {
        return;
    }
    let timeout = remaining.min(Duration::from_millis(25));
    let _ = harness.pump(timeout);
}

fn has_prompt(screen: &str) -> bool {
    screen.lines().any(|line| {
        !is_menu_row(line)
            && (line.contains("PS ")
                || line.trim_end().ends_with('>')
                || line.trim_end().ends_with('$')
                || line.trim_end().ends_with(['', '❯', '❱', 'λ']))
    })
}

fn has_input_echo(screen: &str, expected_line: &str) -> bool {
    // A long native prompt can wrap the ASCII control input onto another row.
    screen
        .lines()
        .filter(|line| !is_menu_row(line))
        .collect::<String>()
        .contains(expected_line)
}

fn is_menu_row(line: &str) -> bool {
    ["› ", "⌘", "≈", "ƒ", "◇", "↳", "−", "□", "▰", "•"]
        .iter()
        .any(|marker| line.contains(marker))
}

fn has_menu_row(screen: &str) -> bool {
    screen.lines().any(is_menu_row)
}

fn has_expected_menu_row(screen: &str, expected: &str) -> bool {
    screen
        .lines()
        .any(|line| is_menu_row(line) && line.contains(expected))
}

fn has_complete_status(screen: &str) -> bool {
    // The fixed benchmark layout reserves a visible status row. Requiring
    // the complete footer rejects diagnostic replacement or clipped status;
    // absence of a loading marker alone cannot prove provider completion.
    screen.lines().any(|line| {
        line.contains(" · ") && line.contains(" · F1 详情") && !line.contains("正在加载")
    })
}

fn host_args(config: &Path, shell: &Path, data_dir: &Path, transport: &str) -> Vec<String> {
    vec![
        "--config".to_owned(),
        config.to_string_lossy().into_owned(),
        "run".to_owned(),
        "--shell".to_owned(),
        shell.to_string_lossy().into_owned(),
        "--data-dir".to_owned(),
        data_dir.to_string_lossy().into_owned(),
        "--transport".to_owned(),
        transport.to_owned(),
    ]
}

fn write_config(path: &Path, descriptions: bool) -> Result<()> {
    let text = format!(
        "[ui]\nwidth = 100\ndescriptions = {descriptions}\nicons = true\nstatus_bar = true\n[completion]\nmax_results = 100\nauto_trigger = true\nfuzzy = true\ndynamic = true\nappend_space = true\n"
    );
    fs::write(path, text).with_context(|| format!("无法写入性能配置 {}", path.display()))?;
    Ok(())
}

fn host_environment(fixtures: &Fixtures) -> Result<BTreeMap<String, String>> {
    let original = env::var_os("PATH").unwrap_or_default();
    let mut paths = vec![fixtures.bin.clone()];
    paths.extend(env::split_paths(&original));
    let path =
        env::join_paths(paths).map_err(|error| anyhow::anyhow!("无法构造夹具 PATH: {error}"))?;
    let pathext = env::var_os("PATHEXT").unwrap_or_else(|| {
        if cfg!(windows) {
            ".COM;.EXE;.BAT;.CMD".into()
        } else {
            "".into()
        }
    });
    Ok(BTreeMap::from([
        ("PATH".to_owned(), path.to_string_lossy().into_owned()),
        ("PATHEXT".to_owned(), pathext.to_string_lossy().into_owned()),
        ("BLUEBERRY_NO_HISTORY".to_owned(), "1".to_owned()),
        ("BLUEBERRY_ACTIVE".to_owned(), "1".to_owned()),
        ("BLUEBERRY_TRACE".to_owned(), "0".to_owned()),
        // Explicitly shadow a caller's diagnostic token.  Harness uses no
        // event tap, and an inherited token must not turn one on in a debug
        // host accidentally.
        ("BLUEBERRY_PROBE_TOKEN".to_owned(), String::new()),
        ("ISTERM".to_owned(), "1".to_owned()),
        ("TERM".to_owned(), "xterm-256color".to_owned()),
    ]))
}

fn create_fixtures(directory: &Path) -> Result<Fixtures> {
    let root = directory.join("fixtures");
    let bin = root.join("bin");
    let git = root.join("git");
    let cargo = root.join("cargo");
    let cargo_app = cargo.join("app");
    let javascript = root.join("javascript");
    let paths = root.join("paths");
    for path in [&bin, &git, &cargo_app, &javascript, &paths] {
        fs::create_dir_all(path).with_context(|| format!("无法创建夹具目录 {}", path.display()))?;
    }

    for index in 0..10 {
        write_command(&bin, &format!("ssbeta-root-{index}"))?;
        write_command(&bin, &format!("ssbeta-fuzzy-{index}"))?;
        fs::create_dir_all(paths.join(format!("ssbeta-path-{index}")))?;
    }
    let throughput = root.join("throughput.txt");
    let mut output = Vec::with_capacity(OUTPUT_BYTES);
    while output.len() < OUTPUT_BYTES {
        output.extend_from_slice(b"blueberry-beta-output\n");
    }
    output.truncate(OUTPUT_BYTES);
    fs::write(&throughput, output)
        .with_context(|| format!("无法写入吞吐夹具 {}", throughput.display()))?;

    let git_global_config = root.join("git-global.config");
    fs::write(&git_global_config, b"[core]\n")?;
    fs::write(git.join("README.txt"), b"Blueberry beta fixture\n")?;
    setup_git(&git, &git_global_config)?;

    write_cargo_fixture(&cargo, &cargo_app)?;
    write_javascript_fixture(&javascript)?;
    Ok(Fixtures {
        root,
        bin,
        git,
        cargo_app,
        javascript,
        paths,
        throughput,
    })
}

fn write_command(bin: &Path, name: &str) -> Result<()> {
    #[cfg(windows)]
    let path = bin.join(format!("{name}.cmd"));
    #[cfg(not(windows))]
    let path = bin.join(name);
    fs::write(&path, b"@echo off\r\n")
        .with_context(|| format!("无法写入命令夹具 {}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(&path)?.permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(&path, permissions)?;
    }
    Ok(())
}

fn setup_git(directory: &Path, global_config: &Path) -> Result<()> {
    fixture_git(directory, global_config, &["init", "-q"])?;
    fixture_git(
        directory,
        global_config,
        &["config", "user.email", "blueberry-beta@example.invalid"],
    )?;
    fixture_git(
        directory,
        global_config,
        &["config", "user.name", "Blueberry Beta Fixture"],
    )?;
    fixture_git(directory, global_config, &["add", "README.txt"])?;
    fixture_git(directory, global_config, &["commit", "-qm", "fixture"])?;
    for index in 0..10 {
        let branch = format!("ssbeta-git-{index}");
        fixture_git(directory, global_config, &["branch", branch.as_str()])?;
    }
    Ok(())
}

fn fixture_git(directory: &Path, global_config: &Path, args: &[&str]) -> Result<()> {
    let output = Command::new("git")
        .current_dir(directory)
        .args(args)
        .env("GIT_CONFIG_GLOBAL", global_config)
        .env("GIT_CONFIG_NOSYSTEM", "1")
        .env("GIT_TERMINAL_PROMPT", "0")
        .env("GCM_INTERACTIVE", "Never")
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .output()
        .with_context(|| format!("无法运行夹具 Git {:?}", args))?;
    ensure!(
        output.status.success(),
        "夹具 Git {:?} 失败: {}",
        args,
        String::from_utf8_lossy(&output.stderr).trim()
    );
    Ok(())
}

fn write_cargo_fixture(workspace: &Path, app: &Path) -> Result<()> {
    let nested = workspace.join("nested").join("member");
    fs::create_dir_all(app.join("src/bin"))?;
    fs::create_dir_all(app.join("examples"))?;
    fs::create_dir_all(app.join("tests"))?;
    fs::create_dir_all(app.join("benches"))?;
    fs::create_dir_all(&nested)?;
    fs::write(
        workspace.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"app\", \"nested/member\"]\nexclude = [\"nested/ignored\"]\n",
    )?;
    let mut manifest = String::from(
        "[package]\nname = \"ssbeta-cargo-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[features]\ndefault = []\n",
    );
    for index in 0..10 {
        manifest.push_str(&format!("ssbeta-cargo-{index} = []\n"));
    }
    manifest.push_str(
        "\n[[bin]]\nname = \"ssbeta-cargo-bin\"\npath = \"src/bin/main.rs\"\n\n[[example]]\nname = \"ssbeta-cargo-example\"\npath = \"examples/example.rs\"\n\n[[test]]\nname = \"ssbeta-cargo-test\"\npath = \"tests/test.rs\"\n\n[[bench]]\nname = \"ssbeta-cargo-bench\"\npath = \"benches/bench.rs\"\n",
    );
    fs::write(app.join("Cargo.toml"), manifest)?;
    fs::write(
        nested.join("Cargo.toml"),
        "[package]\nname = \"ssbeta-cargo-nested\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )?;
    for path in [
        app.join("src/main.rs"),
        app.join("src/bin/main.rs"),
        app.join("examples/example.rs"),
        app.join("tests/test.rs"),
        app.join("benches/bench.rs"),
    ] {
        fs::write(path, "fn main() {}\n")?;
    }
    Ok(())
}

fn write_javascript_fixture(directory: &Path) -> Result<()> {
    let packages = directory.join("packages");
    fs::create_dir_all(packages.join("one"))?;
    let mut scripts = serde_json::Map::new();
    for index in 0..10 {
        scripts.insert(
            format!("ssbeta-js-{index}"),
            Value::String("echo blueberry-beta".to_owned()),
        );
    }
    let package = json!({
        "name": "ssbeta-js-root",
        "private": true,
        "scripts": scripts,
        "workspaces": ["packages/*"],
        "dependencies": {"ssbeta-local": "workspace:*", "safe-runtime": "1.0.0"}
    });
    fs::write(
        directory.join("package.json"),
        serde_json::to_vec_pretty(&package)?,
    )?;
    fs::write(
        directory.join("pnpm-workspace.yaml"),
        "packages:\n  - 'packages/*'\n",
    )?;
    fs::write(
        packages.join("one/package.json"),
        r#"{"name":"ssbeta-js-one","version":"0.1.0","scripts":{"nested":"echo safe"}}"#,
    )?;
    Ok(())
}

fn measure_throughput(
    harness: &mut Harness,
    fixture: &Path,
    session_index: usize,
    mode: &str,
) -> Result<f64> {
    let marker = format!(
        "BLUEBERRY_BETA_OUTPUT_DONE_{mode}_{session_index}_{}",
        uuid::Uuid::new_v4()
    );
    let command = format!(
        "Get-Content -Raw -LiteralPath '{}'; Write-Output '{}'",
        powershell_quote(fixture),
        marker
    );
    let started = Instant::now();
    harness.send(command.as_bytes())?;
    harness.send(b"\r")?;
    wait_for_line(harness, &marker, WAIT_TIMEOUT)?;
    let elapsed = started.elapsed().as_secs_f64().max(f64::EPSILON);
    Ok(OUTPUT_BYTES as f64 / elapsed)
}

fn measure_pwsh_baseline(
    shell: &Path,
    cwd: &Path,
    environment: &BTreeMap<String, String>,
    fixtures: &Fixtures,
) -> Result<Value> {
    let mut baseline_environment = environment.clone();
    baseline_environment.remove("BLUEBERRY_ACTIVE");
    baseline_environment.remove("BLUEBERRY_TRACE");
    // BLUEBERRY_NO_HISTORY is consumed by the adapter and has no meaning to
    // a bare PowerShell process. Explicitly configure PSReadLine after the
    // normal profile has loaded, so this throughput control cannot write the
    // user's history. CI may select a pinned PSReadLine module; load that
    // same module before applying the option to keep the control comparable.
    let mut history_setup = String::new();
    if let Some(module) =
        env::var_os("BLUEBERRY_TEST_PSREADLINE_MODULE").filter(|module| !module.is_empty())
    {
        let module = PathBuf::from(module);
        history_setup.push_str("Import-Module '");
        history_setup.push_str(&powershell_quote(&module));
        history_setup.push_str("' -Force; ");
    }
    history_setup
        .push_str("Import-Module PSReadLine; Set-PSReadLineOption -HistorySaveStyle SaveNothing;");
    let args = vec![
        "-NoLogo".to_owned(),
        "-NoExit".to_owned(),
        "-Command".to_owned(),
        history_setup,
    ];
    let mut harness = Harness::start(
        shell,
        &args,
        cwd,
        &baseline_environment,
        uuid::Uuid::new_v4().to_string(),
    )?;
    wait_for_prompt(&mut harness, WAIT_TIMEOUT)?;
    let mut input_echo = Vec::with_capacity(10);
    for index in 0..10 {
        let line = format!("SS_ECHO_CONTROL_{index}");
        let started = Instant::now();
        harness.send(line.as_bytes())?;
        let deadline = started + WAIT_TIMEOUT;
        loop {
            if has_input_echo(&harness.viewport_contents(), &line) {
                input_echo.push(milliseconds(started.elapsed()));
                break;
            }
            if Instant::now() >= deadline {
                bail!(
                    "独立 PowerShell 输入回显对照超时，样本 {index}；screen:\n{}",
                    harness.viewport_contents()
                );
            }
            pump_brief(&mut harness, deadline);
        }
        reset_line(&mut harness, &line)?;
    }
    let marker = format!("BLUEBERRY_BETA_BASELINE_DONE_{}", uuid::Uuid::new_v4());
    let command = format!(
        "Get-Content -Raw -LiteralPath '{}'; Write-Output '{}'",
        powershell_quote(&fixtures.throughput),
        marker
    );
    let started = Instant::now();
    harness.send(command.as_bytes())?;
    harness.send(b"\r")?;
    wait_for_line(&mut harness, &marker, WAIT_TIMEOUT)?;
    let elapsed = started.elapsed().as_secs_f64().max(f64::EPSILON);
    let throughput = OUTPUT_BYTES as f64 / elapsed;
    harness.finish(WAIT_TIMEOUT)?;
    Ok(json!({
        "throughput": f64_stats(&[throughput], "bytes_per_second"),
        "input_echo_control": f64_stats(&input_echo, "ms"),
        "input_echo_control_note": "10 个编辑后清空、不执行的输入样本，仅诊断；不替代正式宿主热态验收",
        "profile_mode": "preserved",
        "shell": shell,
        "method": "同一 shell、cwd 和固定文本夹具；没有 --no-profile，也没有 Blueberry host",
    }))
}

fn powershell_quote(path: &Path) -> String {
    path.to_string_lossy().replace('\'', "''")
}

fn wait_for_line(harness: &mut Harness, text: &str, timeout: Duration) -> Result<()> {
    let deadline = Instant::now() + timeout;
    loop {
        if harness.contents().lines().any(|line| line.trim() == text) {
            return Ok(());
        }
        if Instant::now() >= deadline {
            bail!(
                "等待输出标记 `{text}` 超时；screen:\n{}",
                harness.viewport_contents()
            );
        }
        // Harness::pump reports a timeout when no PTY bytes arrived in the
        // short interval.  Keep polling until the bounded overall deadline;
        // an EOF is reported with the final screen if the deadline expires.
        pump_brief(harness, deadline);
    }
}

fn adapter_paths(data_dir: &Path) -> BTreeSet<PathBuf> {
    fs::read_dir(data_dir)
        .into_iter()
        .flatten()
        .filter_map(|entry| {
            let path = entry.ok()?.path().join("adapter.json");
            path.is_file().then_some(path)
        })
        .collect()
}

fn wait_for_transport(
    data_dir: &Path,
    requested: &str,
    previous_adapters: &BTreeSet<PathBuf>,
) -> Result<String> {
    let deadline = Instant::now() + Duration::from_secs(2);
    loop {
        if let Ok(entries) = fs::read_dir(data_dir) {
            for entry in entries.flatten() {
                let path = entry.path().join("adapter.json");
                if previous_adapters.contains(&path) {
                    continue;
                }
                let Ok(bytes) = fs::read(&path) else {
                    continue;
                };
                let Ok(value) = serde_json::from_slice::<Value>(&bytes) else {
                    continue;
                };
                if let Some(actual) = value.get("transport").and_then(Value::as_str) {
                    ensure!(
                        matches!(actual, "osc" | "pipe"),
                        "适配器报告未知 transport={actual}（请求 {requested}）"
                    );
                    return Ok(actual.to_owned());
                }
            }
        }
        if Instant::now() >= deadline {
            bail!(
                "等待 adapter.json transport 超时（请求 {requested}）；data_dir={} ",
                data_dir.display()
            );
        }
        thread::sleep(Duration::from_millis(20));
    }
}

fn sample_memory(values: &mut Vec<u64>, harness: &Harness) {
    if let Some(value) = harness.process_id().and_then(working_set_bytes) {
        values.push(value);
    }
}

fn idle_cpu_percent(harness: &Harness) -> Option<f64> {
    let process_id = harness.process_id()?;
    let before = process_cpu_100ns(process_id)?;
    let started = Instant::now();
    thread::sleep(IDLE_CPU_SAMPLE);
    let after = process_cpu_100ns(process_id)?;
    let elapsed_100ns = started.elapsed().as_secs_f64() * 10_000_000.0;
    if elapsed_100ns <= 0.0 {
        return None;
    }
    Some((after.saturating_sub(before) as f64 / elapsed_100ns) * 100.0)
}

#[cfg(windows)]
fn working_set_bytes(process_id: u32) -> Option<u64> {
    use std::mem::size_of;
    use windows_sys::Win32::{
        Foundation::CloseHandle,
        System::{
            ProcessStatus::{K32GetProcessMemoryInfo, PROCESS_MEMORY_COUNTERS},
            Threading::{OpenProcess, PROCESS_QUERY_LIMITED_INFORMATION, PROCESS_VM_READ},
        },
    };
    // SAFETY: the PID comes from the live Harness child, and the handle is
    // closed on every successful OpenProcess path below.
    let handle = unsafe {
        OpenProcess(
            PROCESS_QUERY_LIMITED_INFORMATION | PROCESS_VM_READ,
            0,
            process_id,
        )
    };
    if handle.is_null() {
        return None;
    }
    let mut counters = PROCESS_MEMORY_COUNTERS {
        cb: size_of::<PROCESS_MEMORY_COUNTERS>() as u32,
        ..Default::default()
    };
    // SAFETY: `counters` is a writable value with its documented size.
    let ok = unsafe { K32GetProcessMemoryInfo(handle, &mut counters, counters.cb) != 0 };
    // SAFETY: this handle was returned by OpenProcess and is closed once.
    unsafe { CloseHandle(handle) };
    ok.then_some(counters.WorkingSetSize as u64)
}

#[cfg(not(windows))]
fn working_set_bytes(_process_id: u32) -> Option<u64> {
    None
}

#[cfg(windows)]
fn process_cpu_100ns(process_id: u32) -> Option<u64> {
    use windows_sys::Win32::{
        Foundation::{CloseHandle, FILETIME},
        System::Threading::{GetProcessTimes, OpenProcess, PROCESS_QUERY_LIMITED_INFORMATION},
    };
    // SAFETY: the PID is supplied by the live Harness process.
    let handle = unsafe { OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, 0, process_id) };
    if handle.is_null() {
        return None;
    }
    let mut creation = FILETIME::default();
    let mut exit = FILETIME::default();
    let mut kernel = FILETIME::default();
    let mut user = FILETIME::default();
    // SAFETY: all FILETIME pointers refer to writable local values.
    let ok =
        unsafe { GetProcessTimes(handle, &mut creation, &mut exit, &mut kernel, &mut user) != 0 };
    // SAFETY: this handle was returned by OpenProcess and is closed once.
    unsafe { CloseHandle(handle) };
    ok.then_some(filetime_100ns(kernel).saturating_add(filetime_100ns(user)))
}

#[cfg(not(windows))]
fn process_cpu_100ns(_process_id: u32) -> Option<u64> {
    None
}

#[cfg(windows)]
fn filetime_100ns(value: windows_sys::Win32::Foundation::FILETIME) -> u64 {
    (u64::from(value.dwHighDateTime) << 32) | u64::from(value.dwLowDateTime)
}

fn milliseconds(duration: Duration) -> f64 {
    duration.as_secs_f64() * 1_000.0
}

fn p95_index(length: usize) -> usize {
    // Nearest rank: ceil(0.95 * N), represented as a zero-based index.
    ((length * 95).saturating_add(99) / 100)
        .saturating_sub(1)
        .min(length.saturating_sub(1))
}

fn f64_stats(values: &[f64], unit: &str) -> Value {
    if values.is_empty() {
        return json!({
            "available": false,
            "samples": [],
            "missing": true,
            "unit": unit,
        });
    }
    let mut sorted = values.to_vec();
    sorted.sort_by(f64::total_cmp);
    json!({
        "available": true,
        "samples": values,
        "median": (sorted[(sorted.len() - 1) / 2] + sorted[sorted.len() / 2]) / 2.0,
        "p95": sorted[p95_index(sorted.len())],
        "unit": unit,
    })
}

fn u64_stats(values: &[u64], unit: &str) -> Value {
    if values.is_empty() {
        return json!({
            "available": false,
            "samples": [],
            "missing": true,
            "unit": unit,
        });
    }
    let mut sorted = values.to_vec();
    sorted.sort_unstable();
    let low = sorted[(sorted.len() - 1) / 2] as f64;
    let high = sorted[sorted.len() / 2] as f64;
    json!({
        "available": true,
        "samples": values,
        "median": (low + high) / 2.0,
        "p95": sorted[p95_index(sorted.len())],
        "unit": unit,
    })
}

fn verify_complete_cache(data_dir: &Path) -> Result<bool> {
    let path = data_dir.join("commands.json");
    let bytes =
        fs::read(&path).with_context(|| format!("缺少性能夹具命令缓存 {}", path.display()))?;
    let value: Value = serde_json::from_slice(&bytes)
        .with_context(|| format!("命令缓存不是 JSON: {}", path.display()))?;
    ensure!(
        value.get("complete").and_then(Value::as_bool) == Some(true),
        "命令缓存 {} 未标记 complete=true",
        path.display()
    );
    Ok(true)
}
